import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalContextProvider } from "./context/GlobalContext";
import NavBar from "./components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GlobalContextProvider>
        <body className={`${inter.className}   max-w-[1440px] mx-auto relative bg-black text-white`}>
          <NavBar />
          {children}
        </body>
      </GlobalContextProvider>
    </html>
  );
}
